### PR TITLE
server: fix data race in RaftCluster

### LINKED ISSUE #1270: another data race when running tests
1. What did you do?
`GOCACHE=off make test`

2. What did you expect to see?
test pass

3. What did you see instead?
```
==================
WARNING: DATA RACE
Write at 0x00c00022b698 by goroutine 62:
  github.com/pingcap/pd/server.(*RaftCluster).start()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/cluster.go:116 +0x3af
  github.com/pingcap/pd/server.(*Server).createRaftCluster()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/server.go:420 +0xa3
  github.com/pingcap/pd/server.(*Server).campaignLeader()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/leader.go:246 +0x941
  github.com/pingcap/pd/server.(*Server).leaderLoop()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/leader.go:115 +0x36c

Previous read at 0x00c00022b698 by goroutine 172:
  github.com/pingcap/pd/server.(*RaftCluster).HandleRegionHeartbeat()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/cluster_worker.go:40 +0x1b9
  github.com/pingcap/pd/server.(*Server).RegionHeartbeat()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/grpc_service.go:358 +0x63b
  github.com/pingcap/pd/vendor/github.com/pingcap/kvproto/pkg/pdpb._PD_RegionHeartbeat_Handler()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/pingcap/kvproto/pkg/pdpb/pdpb.pb.go:4013 +0xd0
  github.com/pingcap/pd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.StreamServerInterceptor()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:40 +0x187
  github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:93 +0x12a
  github.com/pingcap/pd/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/server.go:1167 +0x9e0
  github.com/pingcap/pd/vendor/google.golang.org/grpc.(*Server).handleStream()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/server.go:1253 +0x1300
  github.com/pingcap/pd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/server.go:680 +0xac

Goroutine 62 (running) created at:
  github.com/pingcap/pd/server.(*Server).startServerLoop()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/server.go:306 +0x115
  github.com/pingcap/pd/server.(*Server).Run()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/server.go:298 +0xd3
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x279
  fmt.Sscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:114 +0xd0
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:657 +0x1ed
  fmt.Fscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:143 +0xe9
  fmt.Sscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:114 +0xd0
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x144
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x279
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/db_util.go:52 +0x2e4
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/db.go:130 +0xa00
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x279
  fmt.Sscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:114 +0xd0
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x144
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x279
  fmt.Sscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:114 +0xd0
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x144
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x279
  fmt.Sscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:114 +0xd0
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:657 +0x1ed
  fmt.Fscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:143 +0xe9
  fmt.Sscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:114 +0xd0
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x144
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x279
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/db.go:476 +0xe3
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/db.go:125 +0x9dc
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.Open()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/db.go:197 +0x1a0
  fmt.Sscanf()
      /usr/local/Cellar/go/1.11.1/libexec/src/fmt/scan.go:114 +0xd0
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:643 +0x144
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:458 +0x279
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/session.go:113 +0xbb
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/session.go:121 +0x17b7
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.Open()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/db.go:183 +0xd1
  github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/syndtr/goleveldb/leveldb/db.go:219 +0xa5
  github.com/pingcap/pd/server/core.newLeveldbKV()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/core/levedb_kv.go:30 +0x4f
  github.com/pingcap/pd/server/core.NewRegionKV()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/core/region_kv.go:51 +0x5d
  github.com/pingcap/pd/server.(*Server).startServer()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/server.go:213 +0x65c
  github.com/pingcap/pd/server.(*Server).Run()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/server.go:294 +0x89
  github.com/pingcap/pd/server.NewTestServer()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/server/testutil.go:48 +0x9d
  github.com/pingcap/pd/client.(*testClientSuite).SetUpSuite()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/client/client_test.go:66 +0x47
  runtime.call32()
      /usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:522 +0x3a
  reflect.Value.Call()
      /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:308 +0xc0
  github.com/pingcap/pd/vendor/github.com/pingcap/check.(*suiteRunner).runFixture.func1()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/pingcap/check/check.go:747 +0x172
  github.com/pingcap/pd/vendor/github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/github.com/pingcap/check/check.go:692 +0x89

Goroutine 172 (running) created at:
  github.com/pingcap/pd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/server.go:678 +0xb8
  github.com/pingcap/pd/vendor/google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/transport/http2_server.go:416 +0x134d
  github.com/pingcap/pd/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/transport/http2_server.go:456 +0x37a
  github.com/pingcap/pd/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/server.go:676 +0x170
  github.com/pingcap/pd/vendor/google.golang.org/grpc.(*Server).handleRawConn.func2()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/server.go:631 +0x53
  github.com/pingcap/pd/vendor/google.golang.org/grpc.(*Server).handleRawConn.func3()
      /Users/Ryan/PingCAP/go/src/github.com/pingcap/pd/vendor/google.golang.org/grpc/server.go:639 +0x34
==================
```

4. What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?  
When the leader drops which could be caused by some reasons (e.g. cannot read from disk), it will elect a new leader which will call `createRaftCluster` to reassign `cachedCluster`, `coordinator` and `running` in `RaftCluster`. At that time, if we read `RaftCluster` without lock, the data race may happens. This PR closes #1270.

### What is changed and how it works?
This PR adds some locks when reading from `cachedCluster` and `coordinator` in order to prevent reading and writing `RaftCluster` at the same time. 

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to be included in the release notes

### CODE REVIEW

**Comment by disksing** [comment]
Would you explain more details of what's wrong before and how does this PR fix it?

**Comment by disksing** [comment]
Do we need to backport it to 2.1 and 2.0 branch?

**Comment by rleungx** [comment]
@disksing I‘m not sure how much impact it will cause, since it happens rarely.

File: server/cluster_worker.go [hunk 1]
```diff
@@ -27,6 +27,8 @@ import (
 
 // HandleRegionHeartbeat processes RegionInfo reports from client.
 func (c *RaftCluster) HandleRegionHeartbeat(region *core.RegionInfo) error {
+	c.RLock()
```
Comment (nolouch) [inline server/cluster_worker.go]: this lock is in the hot path, can we bench it or remove it?

**Comment by disksing** [comment]
@nolouch @rleungx Any updates?

**Comment by rleungx** [comment]
@disksing After running a benchmark, it doesn't have much impact on performance.
