### PR TITLE
misc: fix the deploy path not being updated

### LINKED ISSUE #2595: Deploy path of the store should be updated
### What did you do?

Move TiKV deploy directory to another place

### What did you expect to see?

The deploy path in the output of pd-ctl store command should be updated.

### What did you see instead?

It is not updated.

### What version of PD are you using (`pd-server -V`)?
master(af5511a359a6cb08f8fdbb2ac7e51429fa0b1314)

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Closes #2595.

### What is changed and how it works?

This PR updates the existed store's deploy path when `Putstore` is called after restarting.

### Check List

Tests

- Unit test

Related changes

- Need to cherry-pick to the release branch

### Release note

- Fix the issue that the deploy path of the store is not updated if the deploy directory is moved

### CODE REVIEW

File: server/core/store_option.go [hunk 1]
```diff
@@ -64,6 +64,15 @@ func SetStoreVersion(githash, version string) StoreCreateOption {
 	}
 }
 
+// SetStoreDeployPath sets the deploy path for the store.
+func SetStoreDeployPath(deployPath string) StoreCreateOption {
+	return func(store *StoreInfo) {
+		meta := proto.Clone(store.meta).(*metapb.Store)
```
Comment (HunDunDM) [inline server/core/store_option.go:70]: Why `Clone` is needed here, it seems that other functions do not do this.

**Comment by HunDunDM** [comment]
LGTM
