### PR TITLE
config: validate dashboard-address

### LINKED ISSUE #2503: Setting dashboard-address in the wrong format can cause unexpected behavior
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

If possible, provide a recipe for reproducing the error.

* Start a cluster
* Use `pd-ctl` to set the dashboard-address config in the wrong format
* Use `pd-ctl` to set the dashboard-address config in the correct format

2. What did you expect to see?

The wrong setting will not have effect, the correct setting will take effect.

3. What did you see instead?

The dashboard is not working properly.

4. What version of PD are you using (`pd-server -V`)?

```bash
Release Version: v4.0.0
Edition: Community
Git Commit Hash: 56d4c3d2237f5bf6fb11a794731ed1d95c8020c2
Git Branch: HEAD
UTC Build Time:  2020-06-02 07:56:57
```

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>

### What problem does this PR solve?

* fix #2503 

### What is changed and how it works?

* When setting the `pd-server` config, validate the `dashboard-address` and reject the incorrect setting.

### Check List

Tests

- Unit test

### CODE REVIEW

File: server/config/config.go [hunk 1]
```diff
@@ -965,6 +965,20 @@ func (c *PDServerConfig) Clone() *PDServerConfig {
 	}
 }
 
+// Validate is used to validate if some pd-server configurations are right.
+func (c *PDServerConfig) Validate() error {
+	switch c.DashboardAddress {
+	case "auto":
```
Comment (lhy1024) [inline server/config/config.go:971]: what mean "auto" and "none"

File: server/config/config_test.go [hunk 2]
```diff
@@ -237,6 +237,71 @@ func newTestScheduleOption() (*PersistOptions, error) {
...
+	tests := []struct {
+		cfgData          string
+		hasErr           bool
+		dashboardAddress string
+	}{
+		{
+			`
+[pd-server]
+dashboard-address = "http://127.0.0.1:2379"
+`,
```
Comment (lhy1024) [inline server/config/config_test.go:250]: format code, plz

File: server/config/config.go (hunk 1 above)
Comment (HunDunDM) [reply server/config/config.go:971]: A specific address represents a specific instance of the running dashboard. `none` represents no instance that has dashboard running, which means that the dashboard is stopped. "auto" means that PD can later decide on an instance of the running dashboard, and after PD is run, it will be replaced with a specific address.

Comment (HunDunDM) [reply server/config/config.go:971]: [Chinese Docs](https://docs.pingcap.com/zh/tidb/v4.0/dashboard-ops-deploy#%E5%88%87%E6%8D%A2%E5%85%B6%E4%BB%96-pd-%E5%AE%9E%E4%BE%8B%E6%8F%90%E4%BE%9B-tidb-dashboard-%E6%9C%8D%E5%8A%A1)

Comment (lhy1024) [reply server/config/config.go:971]: do we need to comment on them to code?

Comment (HunDunDM) [reply server/config/config.go:971]: There is a comment at the definition: `// There are some values supported: "auto", "none", or a specific address, default: "auto"`
