### PR TITLE
*: fix lint tool warnings

### LINKED ISSUE #1171: Fix lint warnings and enable lint options
```
dev :: pingcap/pd » make check
CGO_ENABLED=0 retool sync
gofmt -s -l $(go list ./... | sed 's|github.com/pingcap/pd/||') 2>&1 | awk '{ print } END { if (NR > 0) { exit 1 } }'
retool do govet --shadow $(go list ./... | sed 's|github.com/pingcap/pd/||') 2>&1 | awk '{ print } END { if (NR > 0) { exit 1 } }'
CGO_ENABLED=0 retool do gometalinter.v2 --disable-all --deadline 120s \
  --enable misspell \
  --enable megacheck \
  --enable ineffassign \
  $(go list ./... | sed 's|github.com/pingcap/pd/||')
linting
CGO_ENABLED=0 retool do revive -formatter friendly -config revive.toml $(go list ./...)
  ⚠  confusing-results  unnamed results of the same type may be confusing, consider using named results
  /home/disksing/GOPATH/src/github.com/pingcap/pd/pd-client/client.go:556:1

  ⚠  confusing-results  unnamed results of the same type may be confusing, consider using named results
  /home/disksing/GOPATH/src/github.com/pingcap/pd/pd-client/client.go:572:1

  ⚠  flag-parameter  parameter 'ghost' seems to be a control flag, avoid control coupling
  /home/disksing/GOPATH/src/github.com/pingcap/pd/server/cache/two_queue.go:94:31

  ⚠  confusing-naming  Method 'remove' differs only by capitalization to method 'Remove' in the same source file
  /home/disksing/GOPATH/src/github.com/pingcap/pd/server/cache/lru.go:91:15

  ⚠  flag-parameter  parameter 'b' seems to be a control flag, avoid control coupling
  /home/disksing/GOPATH/src/github.com/pingcap/pd/server/leader.go:42:30

  ⚠  flag-parameter  parameter 'force' seems to be a control flag, avoid control coupling
  /home/disksing/GOPATH/src/github.com/pingcap/pd/server/cluster.go:365:32

  ⚠  confusing-naming  Method 'NewTestServer' differs only by capitalization to function 'newTestServer' in /home/disksing/GOPATH/src/github.com/pingcap/pd/server/server_test.go
  /home/disksing/GOPATH/src/github.com/pingcap/pd/server/testutil.go:42:6

  ⚠  confusing-naming  Method 'listMembers' differs only by capitalization to method 'ListMembers' in the same source file
  /home/disksing/GOPATH/src/github.com/pingcap/pd/server/api/member.go:51:25

  ⚠  flag-parameter  parameter 'isCountReplica' seems to be a control flag, avoid control coupling
  /home/disksing/GOPATH/src/github.com/pingcap/pd/server/schedulers/hot_region.go:202:47

⚠ 9 problems (0 errors, 9 warnings)

Warnings:
  4  flag-parameter
  3  confusing-naming
  2  confusing-results

checking

```

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve? 
Fix the lint warnings reported by `make check`.
Fix #1171

### What is changed and how it works?
- Fix code as suggested.
- Suppress revive in the places that have reason to violate the rules.

### Check List 

Tests 
 - Unit test

### CODE REVIEW

File: server/cache/two_queue.go [hunk 1]
```diff
@@ -91,6 +91,7 @@ func (c *TwoQueue) Put(key uint64, value interface{}) {
 	c.recent.Put(key, value)
 }
 
+// revive:disable-next-line:flag-parameter
```
Comment (rleungx) [inline server/cache/two_queue.go]: Is there a better way to fix this warning?

Comment (gregwebs) [reply server/cache/two_queue.go]: It's possible to just remove this in the linter settings if you don't like this rule. But otherwise this is a good solution for now. I think its better to add the comment here then to continually see the output in the linter.

Comment (disksing) [reply server/cache/two_queue.go]: I think the rule is useful - but not always useful. The method here is not exported and is only used in the `Put` method not far above. I suppose no need to be dogmatic here.

**Comment by disksing** [comment]
PTAL @rleungx
