### PR TITLE
replication_mode: fix config issues

### LINKED ISSUE #2386: updating label key should increase replication version
Otherwise, there is no way to tell if the region is consistency over the old label key or the new label key.

### LINKED ISSUE #2387: cannot set config `dr-auto-sync.primary-replicas`
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
❯ ./bin/pd-ctl config set replication-mode dr-auto-sync primary-replicas 1
Failed! [400] {
  "code": "input",
  "msg": "json: cannot unmarshal string into Go struct field DRAutoSyncReplicationConfig.dr-auto-sync.primary-replicas of type int",
  "data": {
    "Value": "string",
    "Type": {},
    "Offset": 39,
    "Struct": "DRAutoSyncReplicationConfig",
    "Field": "dr-auto-sync.primary-replicas"
  }
}


```

2. What did you expect to see?

set the primary-replicas successfully.

3. What did you see instead?

meet the error.

4. What version of PD are you using (`pd-server -V`)?

,master

### LINKED ISSUE #2388: `dr_auty_sync` can easily be misconfigured
The correct config is:
```
  "replication-mode": "dr_auto_sync",
  "dr-auto-sync": {
    "label-key": "zone",
    "primary": "z1",
    "dr": "z2",
    "primary-replicas": 2,
    "dr-replicas": 1,
    "wait-store-timeout": "1m0s",
    "wait-sync-timeout": "1m0s"
  }
```
as we can see, it uses both `dr_auto_sync` and `dr-auto-sync`. It is not good.

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve? 
Fix #2386 
Fix #2387 
Fix #2388 

### What is changed and how it works?
- change `dr_auto_sync` to `dr-auto-sync` (and auto convert `_` to `-`)
- validate config, if wrong return error
- support pd-ctl set numbers (e.g. primary-replicas)
- switch status to sync_recover when the label key is updated

### Check List 

Tests 
 - Unit test

### CODE REVIEW

File: server/replication/replication_mode.go [hunk 1]
```diff
@@ -21,6 +21,7 @@ import (
 	"sync"
 	"time"
 
+	"github.com/pingcap/kvproto/pkg/replication_modepb"
```
Comment (HunDunDM) [inline server/replication/replication_mode.go:24]: Duplicate import
