### PR TITLE
dashboard: update to fix race bug and add test for it

### LINKED ISSUE #2464: Data race in test
image

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/pd_test/runs/5339/nodes/37/steps/109/log/?start=0

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>

### What problem does this PR solve? 

fix #2464 

### What is changed and how it works?

* dashboard: update to 20200604
* dashboard: add TestCancelDuringStarting

### Check List 

Tests 

 - Unit test

### Release note 

* no release note

### CODE REVIEW

File: pkg/dashboard/adapter/adapter.go [hunk 1]
```diff
@@ -36,31 +35,29 @@ func NewAPIService(srv *server.Server, redirector http.Handler) (*apiserver.Serv
...
-	)
+	dashboardCfg.NormalizePublicPathPrefix()
 
-	return s, nil
+	return dashboardCfg, nil
+}
+
+// GenPDDataProviderConstructor generates a PDDataProviderConstructor for Dashboard API Service.
+func GenPDDataProviderConstructor(srv *server.Server) apiserver.PDDataProviderConstructor {
+	return func(c *config.Config, httpClient *http.Client, etcdClient *clientv3.Client) *region.PDDataProvider {
```
Comment (rleungx) [inline pkg/dashboard/adapter/adapter.go:57]: I think it's better to add a comment about why we need `c *config.Config, httpClient *http.Client` here?

Comment (HunDunDM) [reply pkg/dashboard/adapter/adapter.go:58]: Added a comment
