### PR TITLE
schedule: Do not send an operator of a region wth a stale epoch

### LINKED ISSUE #1652: The number of peers to remove may exceed expectation when timeout happends
There is a bug when dispatching operators of a region with timeout occurs.

Imagine that, when a region requires 3 replicas and it just has 4 in fact. PD found this and create an operator A to remove a replica. Unfortunately, the operator A failed because of timeout. Then PD created another operator B to remove a replica. Rather than time out, the worse thing is that B executed successfully and A was successful in fact too. Indeed, A was timed out, but we don't know if it was executed. We removed 2 replicas finally which is not as expected.

The raft to remove a member is safe relying on the conf version. If two operators try to remove a member with the same conf version, only one can succeed. 

The problem comes from PD.  When there is a region heartbeat from TiKV, PD dispatches the operator of that region, it sends the operator with the region from the heartbeat which may have a newer epoch than when the operator is added, so the old operator will be executed on TiKV because it carries the newest region epoch.

### PR DESCRIPTION
**Pull request by shafreeck**
Signed-off-by: Shafreeck Sea <shafreeck@gmail.com>

### What problem does this PR solve? 
closes #1652

When PD receives a region heartbeat, it dispatches the operator of that region. The dispatching uses the epoch from the heartbeat rather than from the operator when it is created. This causes a bug described in #1652.  

### What is changed and how it works?

If the operator to dispatch has a stale region epoch, cancel it.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: server/schedule/operator_controller.go [hunk 1]
```diff
@@ -93,6 +93,26 @@ func (oc *OperatorController) Dispatch(region *core.RegionInfo, source string) {
...
+			// When the source is heartbeat, the region may have a newer
+			// epoch than the region that the operator holds. In this case,
+			// the operator is stale, and will not be executed even we would
+			// have sent it to TiKV servers. Here, we just cancle it.
+			origin := op.RegionEpoch()
+			latest := region.GetRegionEpoch()
+			changes := (latest.GetVersion() - origin.GetVersion()) +
+				(latest.GetConfVer() - origin.GetConfVer())
+			if source == DispatchFromHeartBeat &&
+				changes > uint64(op.CurrentStep()) {
```
Comment (disksing) [inline server/schedule/operator_controller.go]: It seems to be insufficient to compare version changes to step because there are some steps does not change versions. For example, steps are '[transferLeader, removePeer]', tikv first executes `transferLeader` with no version change, then executes an unexpected `removePeer` which changes version by 1. The region will pass the check here and execute another `removePeer`.

File: server/schedule/operator_controller.go [hunk 2]
```diff
@@ -93,6 +93,26 @@ func (oc *OperatorController) Dispatch(region *core.RegionInfo, source string) {
 		timeout := op.IsTimeout()
 		if step := op.Check(region); step != nil && !timeout {
 			operatorCounter.WithLabelValues(op.Desc(), "check").Inc()
+
+			// When the source is heartbeat, the region may have a newer
+			// epoch than the region that the operator holds. In this case,
+			// the operator is stale, and will not be executed even we would
+			// have sent it to TiKV servers. Here, we just cancle it.
```
Comment (rleungx) [inline server/schedule/operator_controller.go]:
```suggestion
			// have sent it to TiKV servers. Here, we just cancel it.
```

File: server/schedule/operator_controller.go [hunk 3]
```diff
@@ -93,6 +93,26 @@ func (oc *OperatorController) Dispatch(region *core.RegionInfo, source string) {
...
+			origin := op.RegionEpoch()
+			latest := region.GetRegionEpoch()
+			changes := (latest.GetVersion() - origin.GetVersion()) +
+				(latest.GetConfVer() - origin.GetConfVer())
+			if source == DispatchFromHeartBeat &&
+				changes > uint64(op.CurrentStep()) {
+				log.Info("stale operator", zap.Uint64("region-id", region.GetID()),
+					zap.Reflect("operator", op), zap.Uint64("diff", changes))
```
Comment (rleungx) [inline server/schedule/operator_controller.go]: How about printing the differences in both `Version` and `ConfVer`?

File: server/schedule/operator_controller.go (hunk 2 above)
Comment (shafreeck) [reply server/schedule/operator_controller.go]: `cancel` is correct :)

File: server/schedule/operator_controller.go (hunk 1 above)
Comment (shafreeck) [reply server/schedule/operator_controller.go]: I though the epoch will be changed for every operator step. If not, we must record if the epoch would be changed for every step, otherwise, we can not guarantee the atomicity.

Comment (disksing) [reply server/schedule/operator_controller.go]: Yes. It's kind tricky to resolve the problem. I wonder if we can add the expected epoch for each step, when the epoch does not match expected one, we abort the whole operator.

Comment (disksing) [reply server/schedule/operator_controller.go]: Maybe we can sync raft term from tikv to PD to resolve this problem.

Comment (shafreeck) [reply server/schedule/operator_controller.go]: Given that we should add a method for every `OpStep`, the term is unnecessary in fact.

I added a method called `ConsumeConfVer`, which returns the number of conf-version should be consumed if this step was executed. A step does not change the conf-version just return 0.

File: server/schedule/operator/operator.go [hunk 4]
```diff
@@ -101,6 +101,7 @@ func (s StoreInfluence) ResourceSize(kind core.ResourceKind) int64 {
 // OpStep describes the basic scheduling steps that can not be subdivided.
 type OpStep interface {
 	fmt.Stringer
+	ConsumeConfVer() int
```
Comment (disksing) [inline server/schedule/operator/operator.go]: em, I think `Consume` seems hard to understand. Actually, the step does not 'consume' the config version, but trigger the update of config version. How about something like `ExpectConfVarChange() bool`?

Comment (shafreeck) [reply server/schedule/operator/operator.go]: You mean `ExpectConfVerChange() bool`? OK, I also would agree.

File: server/schedule/operator_controller_test.go [hunk 5]
```diff
@@ -180,3 +180,56 @@ func (t *testOperatorControllerSuite) TestStorelimit(c *C) {
...
+
+	// report the result of transferring leader
+	region := cluster.MockRegionInfo(1, 2, []uint64{1, 2},
+		&metapb.RegionEpoch{ConfVer: 0, Version: 0})
+
+	controller.Dispatch(region, DispatchFromHeartBeat)
+	c.Assert(op.ConfVerChanged(), Equals, 0)
+	c.Assert(len(stream.MsgCh()), Equals, 2)
+
+	// report the result of removing perr
```
Comment (rleungx) [inline server/schedule/operator_controller_test.go]:
```suggestion
	// report the result of removing peer
```

File: server/schedule/operator_controller_test.go [hunk 6]
```diff
@@ -180,3 +180,56 @@ func (t *testOperatorControllerSuite) TestStorelimit(c *C) {
...
+	region = cluster.MockRegionInfo(1, 2, []uint64{2},
+		&metapb.RegionEpoch{ConfVer: 0, Version: 0})
+
+	controller.Dispatch(region, DispatchFromHeartBeat)
+	c.Assert(op.ConfVerChanged(), Equals, 1)
+	c.Assert(len(stream.MsgCh()), Equals, 2)
+
+	// add and disaptch op again, the op should be stale
```
Comment (rleungx) [inline server/schedule/operator_controller_test.go]:
```suggestion
	// add and dispatch op again, the op should be stale
```

**Comment by rleungx** [comment]
There is still a type which needs to be fixed. @shafreeck
