### PR TITLE
test: fix flakey TestParseTimestamp

### LINKED ISSUE #665: test: TestParseTimestamp will fail on go1.9+
Using go 1.9 beta 2:
```
FAIL: util_test.go:49: testUtilSuite.TestParseTimestap

util_test.go:55:
    c.Assert(nt, Equals, t)
... obtained time.Time = time.Time{wall:0x5b070ec, ext:63634391568, loc:(*time.Location)(0x156a8a0)} ("2017-06-30 11:52:48.095449324 +0800 CST")
... expected time.Time = time.Time{wall:0xbe4d90a405b070ec, ext:959117978609, loc:(*time.Location)(0x156a8a0)} ("2017-06-30 11:52:48.095449324 +0800 CST m=+959.117978609")
```

Because in go 1.9 time.Time is changed to contain monotonic clock. See https://github.com/golang/proposal/blob/master/design/12914-monotonic.md

### PR DESCRIPTION
**Pull request by choleraehyq**
`t` and `nt` represent the same time instant, yet are not deep equal. `nt` don't have monotonic clock imformation.

Fix #665 

@siddontang PTAL

Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

File: server/util_test.go [hunk 1]
```diff
@@ -52,7 +52,7 @@ func (s *testUtilSuite) TestParseTimestap(c *C) {
 		data := uint64ToBytes(uint64(t.UnixNano()))
 		nt, err := parseTimestamp(data)
 		c.Assert(err, IsNil)
-		c.Assert(nt, Equals, t)
+		c.Assert(nt.Equal(t), IsTrue)
```
Comment (siddontang) [inline server/util_test.go]: The function Equal is in go 1.8?

Comment (choleraehyq) [inline server/util_test.go]: Yes. No API changes.

**Comment by siddontang** [comment]
LGTM
